/// Rule-based outfit suggestions from the user's wardrobe (spec §24–25).
///
/// Every suggestion carries the reasons that produced it; nothing is
/// generated by AI. Scores are relative and only used for ordering.
library;

import 'dart:math' as math;

import 'color_science.dart';
import 'palette_engine.dart';

enum GarmentCategory {
  top,
  bottom,
  onePiece,
  outerwear,
  footwear,
  ethnicTop,
  ethnicBottom,
  accessory,
}

enum GarmentPattern { solid, stripes, checks, print }

enum Occasion { casual, work, formal, festive, sport }

class WardrobeItem {
  const WardrobeItem({
    required this.id,
    required this.name,
    required this.category,
    required this.colorHex,
    this.pattern = GarmentPattern.solid,
    this.formality = 3,
    this.occasions = const {},
    this.favorite = false,
  }) : assert(formality >= 1 && formality <= 5);

  final String id;
  final String name;
  final GarmentCategory category;
  final String colorHex;
  final GarmentPattern pattern;

  /// 1 = very relaxed … 5 = very formal.
  final int formality;

  /// Empty means "any occasion".
  final Set<Occasion> occasions;
  final bool favorite;

  Rgb get color => Rgb.hex(colorHex);
  bool suits(Occasion o) => occasions.isEmpty || occasions.contains(o);
}

enum OutfitReason {
  allNeutral,
  oneAccent,
  tonal,
  analogous,
  complementary,
  inPalette,
  onePattern,
  matchedFormality,
  includesFavourite,
  notWornRecently,
}

class OutfitIdea {
  const OutfitIdea({
    required this.items,
    required this.score,
    required this.reasons,
  });

  final List<WardrobeItem> items;
  final double score;
  final List<OutfitReason> reasons;

  String get key => (items.map((i) => i.id).toList()..sort()).join('+');
}

abstract final class OutfitEngine {
  /// Typical formality for an occasion.
  static int targetFormality(Occasion o) => switch (o) {
        Occasion.sport => 1,
        Occasion.casual => 2,
        Occasion.work => 3,
        Occasion.festive => 4,
        Occasion.formal => 5,
      };

  /// Up to [limit] outfits for [occasion], best first.
  /// [recentlyWorn] item ids lower a combination's score for variety.
  static List<OutfitIdea> suggest({
    required List<WardrobeItem> wardrobe,
    required Occasion occasion,
    Palette? palette,
    Set<String> recentlyWorn = const {},
    int limit = 6,
  }) {
    final fit = wardrobe.where((i) => i.suits(occasion)).toList();
    List<WardrobeItem> of(Set<GarmentCategory> cats) =>
        fit.where((i) => cats.contains(i.category)).toList();

    final tops = of({GarmentCategory.top, GarmentCategory.ethnicTop});
    final bottoms = of({GarmentCategory.bottom, GarmentCategory.ethnicBottom});
    final pieces = of({GarmentCategory.onePiece});
    final outer = of({GarmentCategory.outerwear});
    final shoes = of({GarmentCategory.footwear});

    // Base combinations: top + bottom, or a one-piece.
    final bases = <List<WardrobeItem>>[
      for (final t in tops)
        for (final b in bottoms) [t, b],
      for (final p in pieces) [p],
    ];
    final candidates = <List<WardrobeItem>>[];
    for (final base in bases) {
      final withShoes = shoes.isEmpty
          ? [base]
          : [for (final s in shoes) [...base, s]];
      for (final c in withShoes) {
        candidates.add(c);
        // Outer layer for work and formal, or when it improves the look.
        for (final o in outer) {
          candidates.add([...c, o]);
        }
      }
    }

    final target = targetFormality(occasion);
    final ideas = <OutfitIdea>[];
    for (final items in candidates) {
      final idea = _score(items, target, palette, recentlyWorn);
      if (idea != null) ideas.add(idea);
    }
    ideas.sort((a, b) => b.score.compareTo(a.score));

    // Diversity: avoid near-duplicates that share the same base.
    final out = <OutfitIdea>[];
    final usedBases = <String>{};
    for (final idea in ideas) {
      final base = idea.items
          .where((i) => i.category != GarmentCategory.footwear &&
              i.category != GarmentCategory.outerwear)
          .map((i) => i.id)
          .join('+');
      if (!usedBases.add(base)) continue;
      out.add(idea);
      if (out.length >= limit) break;
    }
    return out;
  }

  static OutfitIdea? _score(List<WardrobeItem> items, int target,
      Palette? palette, Set<String> recent) {
    final reasons = <OutfitReason>[];
    var score = 0.0;

    // Patterns: more than one competes for attention.
    final patterned = items.where((i) => i.pattern != GarmentPattern.solid).length;
    if (patterned > 1) return null;
    if (patterned == 1) {
      score += 0.2; // allowed, not rewarded
      reasons.add(OutfitReason.onePattern);
    }

    // Colour harmony.
    final colors = [for (final i in items) i.color];
    switch (harmonyOf(colors)) {
      case Harmony.clash:
        return null;
      case Harmony.neutral:
        // All-neutral looks are classic, especially for work and formal.
        score += target >= 3 ? 2.3 : 1.7;
        reasons.add(OutfitReason.allNeutral);
      case Harmony.monochrome:
        final accents = colors.where((c) => !isNeutral(c)).length;
        score += 2.0;
        reasons.add(accents == 1 ? OutfitReason.oneAccent : OutfitReason.tonal);
      case Harmony.analogous:
        score += 1.6;
        reasons.add(OutfitReason.analogous);
      case Harmony.complementary:
        score += 1.4;
        reasons.add(OutfitReason.complementary);
    }

    // Formality: items should agree with each other and the occasion.
    final f = [for (final i in items) i.formality];
    final spread = f.reduce(math.max) - f.reduce(math.min);
    if (spread > 2) return null;
    // Under-dressing for an occasion costs more than being a little smarter
    // than needed, and one very casual piece spoils a smart look.
    // Dressing down matters at work and formal events, much less casually.
    final under = target >= 3 ? 1.0 : 0.4;
    final pens = [
      for (final x in f) x < target ? (target - x) * under : (x - target) * 0.4,
    ];
    final meanPen = pens.reduce((a, b) => a + b) / pens.length;
    final worst = pens.reduce(math.max);
    score += 2.0 - meanPen - 0.5 * worst - 0.6 * math.max(0, spread - 1);
    if (spread <= 1 && worst <= 0.8) reasons.add(OutfitReason.matchedFormality);
    if (target >= 3 &&
        items.any((i) => i.category == GarmentCategory.outerwear)) {
      score += 0.4; // a layer finishes smart looks
    }

    // Personal palette, for colours near the face (tops and one-pieces).
    if (palette != null) {
      final nearFace = items.where((i) =>
          i.category == GarmentCategory.top ||
          i.category == GarmentCategory.ethnicTop ||
          i.category == GarmentCategory.onePiece);
      if (nearFace.isNotEmpty) {
        final pf = nearFace.map((i) => palette.fit(i.color)).reduce(math.min);
        score += pf * 1.5;
        if (pf >= 0.6) reasons.add(OutfitReason.inPalette);
      }
    }

    if (items.any((i) => i.favorite)) {
      score += 0.4;
      reasons.add(OutfitReason.includesFavourite);
    }
    final worn = items.where((i) => recent.contains(i.id)).length;
    if (worn == 0 && recent.isNotEmpty) {
      score += 0.6;
      reasons.add(OutfitReason.notWornRecently);
    } else {
      score -= worn * 1.5;
    }
    // Complete looks (with shoes) rank above partial ones.
    if (items.any((i) => i.category == GarmentCategory.footwear)) score += 0.5;

    return OutfitIdea(items: items, score: score, reasons: reasons);
  }
}
